# Generated by Django 4.2.23 on 2025-07-16 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('poster_url', models.URLField()),
                ('rating', models.FloatField()),
                ('total_reviews', models.IntegerField()),
                ('watchers', models.IntegerField()),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=100)),
                ('alt_titles', models.TextField()),
                ('episodes', models.IntegerField()),
                ('aired', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('content_rating', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('popularity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars/')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('points', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(default='Member', max_length=30)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
