# Generated by Django 4.2.23 on 2025-07-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_userprofile_avatar_remove_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='actors/')),
                ('biography', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='drama',
            old_name='aired',
            new_name='original_network',
        ),
        migrations.RenameField(
            model_name='drama',
            old_name='alt_titles',
            new_name='storyline',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='content_rating',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='country',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='description',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='director',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='network',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='watchers',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='year',
        ),
        migrations.AddField(
            model_name='drama',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='dramas/'),
        ),
        migrations.AddField(
            model_name='drama',
            name='release_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='drama',
            name='streaming_platforms',
            field=models.CharField(default='Not Available', max_length=200),
        ),
        migrations.AlterField(
            model_name='drama',
            name='tags',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='DramaActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.actor')),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.drama')),
            ],
        ),
        migrations.AddField(
            model_name='drama',
            name='actors',
            field=models.ManyToManyField(to='Home.actor'),
        ),
    ]
