# Generated by Django 4.2.23 on 2025-07-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_actor_rename_aired_drama_original_network_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drama',
            old_name='storyline',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='original_network',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='streaming_platforms',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='tags',
        ),
        migrations.AddField(
            model_name='drama',
            name='category',
            field=models.CharField(choices=[('drama', 'Drama'), ('variety', 'Variety Show'), ('movie', 'Movie'), ('anime', 'Anime')], default='drama', max_length=50),
        ),
        migrations.AddField(
            model_name='drama',
            name='country',
            field=models.CharField(choices=[('korea', 'Korea'), ('china', 'China'), ('japan', 'Japan'), ('thailand', 'Thailand'), ('philippines', 'Philippines')], default='korea', max_length=50),
        ),
        migrations.AddField(
            model_name='drama',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='drama',
            name='status',
            field=models.CharField(choices=[('trending', 'Trending'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('ongoing', 'Ongoing')], default='completed', max_length=50),
        ),
        migrations.AlterField(
            model_name='drama',
            name='genre',
            field=models.CharField(help_text='Separate multiple genres with commas (e.g. Romance, Action)', max_length=255),
        ),
        migrations.AlterField(
            model_name='drama',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drama_images/'),
        ),
        migrations.AlterField(
            model_name='drama',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
