# Generated by Django 4.2.23 on 2025-07-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_storyline_drama_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dramaactor',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='dramaactor',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='description',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='image',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='status',
        ),
        migrations.AddField(
            model_name='drama',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drama',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drama',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='DramaActor',
        ),
    ]
