# Generated by Django 4.2.23 on 2025-07-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='dob',
        ),
        migrations.AddField(
            model_name='actor',
            name='born',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actors/'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
