# Generated by Django 4.2.23 on 2025-07-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_remove_actor_dob_actor_born_actor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
