# Generated by Django 4.2.23 on 2025-07-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_actor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='category',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='release_date',
        ),
        migrations.AddField(
            model_name='drama',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='episodes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='drama',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drama',
            name='release_year',
            field=models.CharField(default='2000', max_length=4),
        ),
        migrations.AddField(
            model_name='drama',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
        ),
        migrations.AddField(
            model_name='drama',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='drama',
            name='trailer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='type',
            field=models.CharField(default='Drama', max_length=50),
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='drama',
            name='country',
            field=models.CharField(default='Korea', max_length=50),
        ),
        migrations.AlterField(
            model_name='drama',
            name='genre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='drama',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
