# Generated by Django 4.2.23 on 2025-07-24 07:51

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0012_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='content_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('user', 'content_type', 'content_id')},
        ),
    ]
