# Generated by Django 4.2.23 on 2025-07-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_watchlistitem_added_on_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='content_type',
            field=models.CharField(choices=[('drama', 'Drama'), ('movie', 'Movie'), ('variety', 'Variety Show')], max_length=20),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='episodes_watched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='content_id',
        ),
    ]
